#ifndef CBECRYPTO_ERROR_H_
#define CBECRYPTO_ERROR_H_

enum cbecrypto_error {
    CBECRYPTO_SUCCESS = 0,
    CBECRYPTO_ERR_FAIL_ALLOC,
    CBECRYPTO_ERR_NULL_CTX_PTR,
    CBECRYPTO_ERR_NO_SPES,
    CBECRYPTO_ERR_IO,
};

#endif /*CBECRYPTO_ERROR_H_*/
